; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[app]
build_flags =
   -D NOME_ID=\"caixa_agua\"

   ;D8
   -D DEFAULT_RELE_PIN=5
   ;D2
   -D DEFAULT_BUTTON_PIN=4
   -D ENBALED_BUTTON_PIN
   -D ENABLED_SERIAL
   -D MAX_TIMED_ON_MINUTES=60
   -D ESPALEXA_MAXDEVICES=1

[env:lampada_d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_raw = yes

; Configurações específicas para o ESP8266
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L
upload_speed = 921600


lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  aircoookie/Espalexa@^2.7.0
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.4.3
  WebSockets

  
build_flags =
    ${app.build_flags}
    ;-D ESPALEXA_DEBUG
    -D LAMPADA_APP

[env:nivel_agua_d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_raw = yes

; Configurações específicas para o ESP8266
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L
upload_speed = 921600


lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  aircoookie/Espalexa@^2.7.0
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.4.3
  WebSockets

  
build_flags =
    ${app.build_flags}
    ;-D ESPALEXA_DEBUG
    -D NIVEL_AGUA_APP
    ; 5 minutos em ms - ZERO desabilita
    -D LOOP_INTERVALO=60000
    ; 60 * 1000000 ms = 1 minuto - ZERO desabilita
    -D LOOP_DEEP_SLEEP=0 ;1 ;60  ; em segundos 

src_filter = 
    +<*>
    -<nivel_agua/exemplo_uso.cpp>
